<?php

use NixPHP\Form\Core\Validator;
use function NixPHP\I18n\t;
use function NixPHP\View\asset;
use function NixPHP\View\view;

/* @var array $data */
/* @var Validator $validator */
?>

<?php $this->setLayout('layout') ?>

<?php $this->block('content') ?>

    <div id="episode-form" class="hidden">
        <?= view('components/episode-form', ['data' => $data, 'validator' => $validator]) ?>
    </div>

    <a class="modal-trigger" data-target="#episode-form" href="javascript:"><?= t('link.add-episode') ?></a>

<?php $this->endblock('content') ?>

<?php asset()->add('/assets/js/modal.nix.js') ?>
